### PR TITLE
move br0 to interfaces, disable resolvconf

### PR DESCRIPTION
**Pull request by georgejhunt**
testing to date:
applied to Josh's pixel and pixel-lite images. results:
   pixel: reboot went from 3:02 to 0:44
   lite: reboot went from 3:55 to 0:31
without ethernet: pixel reboots in 0:31
"box" and "box.lan" still resolve on attached client

No testing on other-than-rpi

### CODE REVIEW

**Comment by tim-moody** [comment]
for gateway you changed eth0 from dhcp to manual. are you sure you get an ip address when it is connected?

**Comment by georgejhunt** [comment]
That seems to be the whole function of dhcpcd. But specifying manual, the
networking.service is instructed to let dhcpcd do it.

**Comment by jvonau** [comment]
Please remove the now unused template files. Should the APPLIANCE section receive the same treatment? Sounds more like a race for control of the network card. Something is not quite right, network.service using dhcp in the interface file should call a dhcp client daemon without manually enabling the dhcpdcd service. If the dhcpcd.service is enabled and has been started before network.service then there will be a stall while network.service is trying to enable and the take control of the card then can't. Same holds true during shutdown. Have a closer look at the logs.

**Comment by jvonau** [comment]
There is a typo in rpi_debian.yml also:  "command: ifdown etho"

**Pull request merged**
