### PR TITLE
Mar22 take2

### PR DESCRIPTION
**Pull request by jvonau**
Replacing PR #244

### CODE REVIEW

**Comment by georgejhunt** [comment]
Does this mean that kiwix is not available for i686?

**Comment by jvonau** [comment]
There is no i686 listed to download or on the website.

**Comment by tim-moody** [comment]
The changes to kalite will break the install.

The principal is that we always install and then either enable or disable services.  kalite needs to be running in order for the install to complete.  that’s why it was started in two places.

**Comment by jvonau** [comment]
How does this break the install when you always have to run install.yml
then always run enable.yml? What will fail is if you don't install kalite
by default then try to disable the non-existent service in enable.yml

**Comment by jvonau** [comment]
I'm closing this one as the last 2 commits were unintended going to redo

**Comment by tim-moody** [comment]
sorry, think I confused this with owncloud where the service actually has to be running during the configuration step of the install.

**Pull request closed without merging**
