### PR TITLE
Wifi

### PR DESCRIPTION
**Pull request by georgejhunt**
eliminate testing confusion with multiple wifi units on my desk

### CODE REVIEW

**Comment by tim-moody** [comment]
actual values for a deployment would go in local_vars, right?
which wifi does this refer to, internal WAN, internal LAN AP, external AP?

**Comment by tim-moody** [comment]
what about password?

**Comment by georgejhunt** [comment]
This refers to hostapd, which is the internal lan. Yes local_vars is where
this would be set

For the internal wan on an xo1.5 we can continue to use gui  from the OLPC
network neighborhood.

External AP can be administered by whatever AP is used, and it's normal
config process

**Comment by georgejhunt** [comment]
Password for our internal AP is complicated by setting up wpa_supplicant.
Maybe it will be necessary long term, but open seems ok to me for this
release.

**Comment by tim-moody** [comment]
could the variables be named to indicate that this is hostap_ssid, etc.  we might one day have wan_ssid

**Comment by georgejhunt** [comment]
I guess I should spend the time now to work our psk2 passwords for hostapd.
I'll put it on my list.

**Pull request merged**
