### PR TITLE
Mar25 fixes

### PR DESCRIPTION
**Pull request by jvonau**
Replaces PR #245

### CODE REVIEW

**Comment by tim-moody** [comment]
I'm of two minds on error trapping like is done for kiwix.  Not having errors which cause the thing to halt is always good, but here you will get no notice if kiwix download is not found and will be left wondering what happened.  Can we have a debug message?

**Comment by jvonau** [comment]
The behavior didn't change, the playbook doesn't run if kiwix_src_file is
undefined. Didn't think a error was needed if run on i686, you'll see
"skipping".

**Comment by tim-moody** [comment]
if it’s undefined you’re on an unsupported platform, so I think it should crash.  There are hundreds of skipping messages.

**Comment by jvonau** [comment]
meet halfway with a warning, no fail

**Comment by jvonau** [comment]
Replaced by PR #252

**Pull request closed without merging**
