### PR TITLE
Raspbian 6.1

### PR DESCRIPTION
**Pull request by georgejhunt**
I was doubtful this morning that I'd be able to pull this off. But this is a clean set of diffs based upon release-6.1 as of this moment.  It creates a working image on rpi3.
I do not propose to pull this into release-6.1, but rather keep it as a branch that can be applied to the current last-release. If everyone approves, I'd like to create this branch in XSCE main repo.
So in my mind, at least, this is not a fork. It's my intention to continue to do most of my work on master.

### CODE REVIEW

**Comment by jvonau** [comment]
Works for me


Sent from Samsung Mobilegeorgejhunt <notifications@github.com> wrote:I was doubtful this morning that I'd be able to pull this off. But this is a clean set of diffs based upon release-6.1 as of this moment. It creates a working image on rpi3.
I do not propose to pull this into release-6.1, but rather keep it as a branch that can be applied to the current last-release. If everyone approves, I'd like to create this branch in XSCE main repo.
So in my mind, at least, this is not a fork. It's my intention to continue to do most of my work on master.

You can view, comment on, or merge this pull request online at:

  https://github.com/XSCE/xsce/pull/824

Commit Summary

substitute package for yum module
state=installed needs to become present
clean ups
capture some progress
pip does not compile without redhat-rpm-config
changes let ansible run to console successfully -- apache does not serve console
httpd->apache2
working on named->bind0
pip needs redhat-rpm
armv7hl->armv7l
start the day with a captured state
create a network config directory variable in ansible
add in the config files
got through network role without error
debian does not put ansible in same place as fedora. Make a variable for ansible prefix
still working on daemon startup
xs-portal and home work
authexternal pwauth
give up on dansguardian, install kiwix
working on mysql, no systemd yet
small fixes
debian changes apache->www-data
do not install stuff that is not useful as client
debian name change
spell postgresql
more complete list not to install
disable authserver
debian calls it mysql
fix mysq
add in mysql for debian
substitute package for yum module
state=installed needs to become present
working on named->bind0
disable iiab install
add in a cli console script
record wsgi socket solution
systemV stuff
fix merge conflicts
start the day with a captured state
add in the config files
got through network role without error
xs-portal and home work
debian name change
spell postgresql
more complete list not to install
fix mysq
remove xs-config in http role
daemon does not exist in debian
postres initdb is in different place
samba names change nmb ->mnbd
capture some progress
network interfaces, cmdsrv fixes
simplify decision on eth0 under bridge -- base it upon LanController
add in schooltool
fix bind9
remote admin of cups, many changes apache->www-data as owner for apache2 access
schooltool needs font dir
fixes to get to console
Create debian.md
let ansible be anywhere,load standard stuff via yum.yml, blash Gateway into gui_desired_network_role
fix the command server that I broke merging files -- missing if statement
enable the en_US locale for rpi3 -- only en_GB -- manufactured in GB
smb->smdd, lineinfile path->dest, locale fix in postgresql
capture fixes to moodle,postgresql,schooltool,squid,dansguardian
awstats works with schoolserver/awstats/awstats.pl but not schoolserver.lan. . . -- still need to integrate squid logs into report
necessary to run to completing
fixes for iiab-openstreetmap
we need uuidgen
iiab defaults missing
get_url->wget. work a lot faster
File Changes

M ansible_hosts (1)
A console_cli.sh (44)   
A docs/debian.md (2)
M install-console (2)   
M install-init.yml (2)  
M roles/0-once/tasks/centos.yml (4)
M roles/0-once/tasks/chrony.yml (4)
M roles/0-once/tasks/cmdsrv.yml (12)
M roles/0-once/tasks/fedora.yml (4)
M roles/0-once/tasks/hw_rpi2.yml (13)
M roles/0-once/tasks/main.yml (15)
M roles/0-once/tasks/prep.yml     (4)
M roles/0-once/tasks/xo.yml (4)
M roles/0-once/tasks/yum.yml     (33)
M roles/0-once/templates/local_facts.fact.j2 (6)
M roles/1-prep/tasks/computed_vars.yml (5)
M roles/1-prep/tasks/detected_network.yml (3)
M roles/1-prep/tasks/raspberry_pi_2.yml (8)
M roles/3-base-server/tasks/main.yml (2)
M roles/4-server-options/tasks/main.yml (6)
M roles/7-edu-apps/meta/main.yml (2)
M roles/activity-server/tasks/main.yml (4)
M roles/ajenti/tasks/main.yml (8)
M roles/authserver/tasks/main.yml (9)
M roles/authserver/templates/xs-authserver.service.j2     (2)
M roles/awstats/tasks/install.yml (47)
A roles/awstats/templates/apache.conf (51)
M roles/awstats/templates/awstats.schoolserver.conf.j2 (4)
M roles/calibre/tasks/main.yml (6)
M roles/calibre/templates/calibre-serve.service.j2 (2)
M roles/cups/tasks/main.yml (8)
A roles/cups/templates/cupsd.conf (84)
A roles/debian_schooltool/defaults/main.yml (5)
A roles/debian_schooltool/tasks/main.yml     (48)
A roles/debian_schooltool/templates/buildout.cfg (26)
M roles/docker/tasks/main.yml (3)
M roles/dokuwiki/tasks/install.yml (22)
M roles/ejabberd/tasks/main.yml (4)
M roles/elgg/tasks/main.yml (18)
M roles/httpd/tasks/main.yml (60)
D roles/httpd/templates/xs-console.conf.j2     (1)
M roles/idmgr/tasks/main.yml (4)
M roles/iiab/tasks/main.yml (40)
A roles/iiab/templates/defaults.ini (82)
M roles/iiab/templates/iiab.conf.j2 (4)
M roles/kalite/defaults/main.yml (4)
M roles/kalite/tasks/assessment.yml (2)
M roles/kalite/tasks/install-f18.yml (4)
M roles/kalite/tasks/install.yml (8)
M roles/kalite/tasks/main.yml (6)
M roles/kalite/tasks/setup.yml (4)
M roles/kalite/templates/kalite-serve.service.j2 (4)
M roles/kiwix/tasks/kiwix_install.yml (4)
M roles/kiwix/tasks/main.yml (19)
M roles/mongodb/tasks/main.yml (3)
M roles/monit/tasks/main.yml (4)
M roles/monit/templates/httpd (6)
M roles/moodle-1.9/moodle/tasks/main.yml (10)
M roles/moodle-1.9/moodle/templates/moodle-xs.service.in (2)
M roles/moodle-1.9/moodle/templates/moodle-xs.service.j2 (2)
M roles/moodle/tasks/main.yml (47)
M roles/moodle/templates/moodle_installer (2)
M roles/munin/tasks/main.yml (4)
M roles/mysql/tasks/centos.yml (3)
A roles/mysql/tasks/debian.yml (10)
M roles/mysql/tasks/fedora.yml (3)
M roles/mysql/tasks/main.yml (26)
M roles/network/defaults/main.yml (3)
M roles/network/tasks/avahi.yml (27)
M roles/network/tasks/dansguardian.yml (10)
A roles/network/tasks/debian.yml (32)
M roles/network/tasks/dhcpd.yml (10)
M roles/network/tasks/enable_services.yml (17)
M roles/network/tasks/iptables.yml (22)
M roles/network/tasks/main.yml (7)
M roles/network/tasks/named.yml (48)
M roles/network/tasks/restart.yml (15)
M roles/network/tasks/squid.yml (49)
M roles/network/tasks/wondershaper.yml (5)
M roles/network/templates/dhcp/dhcpd.service (2)
M roles/network/templates/gateway/xs-gen-iptables (8)
M roles/network/templates/hostapd/hostapd.conf.j2 (1)
A roles/network/templates/named/bind9.service (13)
M roles/network/templates/named/named (2)
A roles/network/templates/network/br0.j2 (40)
A roles/network/templates/squid/dansguardian.conf.debian.j2 (625)
M roles/openvpn/tasks/main.yml (17)
M roles/openvpn/templates/announcer (4)
A roles/openvpn/templates/up_wan (9)
M roles/openvpn/templates/xs-handle (1)
M roles/owncloud/tasks/main.yml (16)
M roles/owncloud/tasks/owncloud_enabled.yml (15)
M roles/pathagar/tasks/main.yml (30)
M roles/pathagar/templates/pathagar.conf (2)
M roles/phpmyadmin/tasks/main.yml (10)
M roles/portal/handlers/main.yml (2)
M roles/portal/tasks/main.yml (16)
M roles/portal/tasks/xs-portal.yml (10)
M roles/portal/templates/xs-portal.conf (2)   
M roles/postgresql/tasks/main.yml (18)
M roles/postgresql/templates/postgresql-xs.service (39)
M roles/rachel/tasks/rachel_enabled.yml (16)
M roles/samba/handlers/main.yml (2)
M roles/samba/tasks/main.yml (11)
M roles/schooltool/tasks/main.yml (2)
M roles/sugar-stats/tasks/main.yml (4)
M roles/sugar-stats/tasks/statistics-consolidation.yml     (8)
M roles/sugarizer/tasks/main.yml (12)
A roles/sugarizer/templates/sugarizer.conf (4)
M roles/teamviewer/tasks/install.yml (4)
M roles/vnstat/tasks/main.yml (4)
M roles/wordpress/defaults/main.yml (2)
M roles/wordpress/tasks/install.yml (21)
M roles/xovis/tasks/main.yml (4)
M roles/xsce-admin/files/cmdsrv/xsce-cmdsrv (24)
M roles/xsce-admin/tasks/access.yml (4)
M roles/xsce-admin/tasks/admin-user.yml (6)
M roles/xsce-admin/tasks/cmdsrv.yml (80)
M roles/xsce-admin/tasks/console.yml (38)
A roles/xsce-admin/templates/cmdsrv/cmdsrv.py (28)
M roles/xsce-admin/templates/cmdsrv/xsce-cmdsrv-init.j2 (25)
M roles/xsce-admin/templates/cmdsrv/xsce-cmdsrv.service.j2 (2)   
M roles/xsce-admin/templates/console/xs-console.conf.j2 (5)
A vars/debian.yml (26)
M xsce-base.yml (2)   
M xsce-from-console.yml (2)
M xsce-network.yml     (2)
M xsce.yml (2)
Patch Links:

https://github.com/XSCE/xsce/pull/824.patch
https://github.com/XSCE/xsce/pull/824.diff

**Comment by tim-moody** [comment]
I thought your position was only fixes into 6.1, but this looks like a ton of new stuff into 6.1. I would not be able to use this without changes and extensive testing in Lebanon and it contains conflicts with things I planned for 6.2.

**Comment by jvonau** [comment]
Think George is wanting to have the branch on XSCE where he can maintain it
openly. This branch is clean against 6.1 so if anything gets pushed to 6.1
it would need to be rebased but that is maintainable. With the 'package'
change I'm not sure if that is debain specific or is distro agnostic but
restricted to ansible 2.0+. Please advice if you have info on the subject.
We have all the variable available to make some choices in what path to
take code wise just have to make it all work in master at some point.

**Comment by tim-moody** [comment]
As it stands this PR is from ghunt:raspbian-6.1 to XSCE:release-6.1.  Maybe this is a typo.

**Comment by georgejhunt** [comment]
I created a PR into 6.1 as a convenience for documenting the diffs.

So I will delete this PR, and push my raspbian-6.1 branch directly into
github.com/XSCE. Is that ok with Tim?

**Comment by tim-moody** [comment]
my confusion is that your original text says this would be a branch on xsce but the pull is into release-6.1
if you want an xsce -b raspian-6.1, I don't object, but I do object to merging this PR into release-6.1

**Comment by georgejhunt** [comment]
agreed

**Comment by georgejhunt** [comment]
I'll push this branch directly to github.com/XSCE

**Pull request closed without merging**
