### PR TITLE
Merge gateway into Network

### PR DESCRIPTION
**Pull request by jvonau**
There's a lot of work represented here. I like it. I think we should pull it.
On my NUC, on FC21, ssh.service is  not in /etc/avahi/services/. In order to proceed I copied it from /usr/share/doc/avahi/ssh.service to the location required by the playbook. Maybe it should be a template.

### CODE REVIEW

**Comment by tim-moody** [comment]
on x64 vm with two nics; install-console

TASK: [network | Enable named service] ****************************************
failed: [127.0.0.1] => {"failed": true}
msg: Job for named.service failed. See 'systemctl status named.service' and 'journalctl -xn' for details.


FATAL: all hosts have already failed -- aborting

named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled)
   Active: failed (Result: exit-code) since Mon 2015-03-16 15:52:08 EDT; 10min ago
  Process: 1536 ExecStart=/usr/sbin/named -u named $OPTIONS (code=exited, status=1/FAILURE)
  Process: 1535 ExecStartPre=/usr/sbin/named-checkconf -z /etc/named.conf (code=exited, status=0/SUCCESS)

Mar 16 15:52:08 schoolserver.lan systemd[1]: Starting Berkeley Internet Name Domain (DNS)...
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone localhost.localdomain/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone localhost/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 0.in-addr.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named[1539]: starting BIND 9.9.4-P2-RedHat-9.9.4-18.P2.fc20 -u named -4 -c /etc/named-xs.conf
Mar 16 15:52:08 schoolserver.lan named[1539]: built with '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-libtool' '--localstatedir=/var' '--enable-threads' '--enable-ipv6' '--enable-filter-aaaa' '--enable-rrl' '--with-pic' '--disable-static' '--disable-openssl-version-check' '--enable-exportlib' '--with-export-libdir=/usr/lib64' '--with-export-includedir=/usr/include' '--includedir=/usr/include/bind9' '--with-pkcs11=/usr/lib64/pkcs11/PKCS11_API.so' '--with-dlz-ldap=yes' '--with-dlz-postgres=yes' '--with-dlz-mysql=yes' '--with-dlz-filesystem=yes' '--with-dlz-bdb=yes' '--with-gssapi=yes' '--disable-isc-spnego' '--enable-fixed-rrset' '--with-docbook-xsl=/usr/share/sgml/docbook/xsl-stylesheets' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS= -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CPPFLAGS= -DDIG_SIGCHASE'
Mar 16 15:52:08 schoolserver.lan named[1539]: ----------------------------------------------------
Mar 16 15:52:08 schoolserver.lan named[1539]: BIND 9 is maintained by Internet Systems Consortium,
Mar 16 15:52:08 schoolserver.lan systemd[1]: named.service: control process exited, code=exited status=1
Mar 16 15:52:08 schoolserver.lan systemd[1]: Failed to start Berkeley Internet Name Domain (DNS).
Mar 16 15:52:08 schoolserver.lan systemd[1]: Unit named.service entered failed state.

Mar 16 15:51:36 schoolserver.lan ansible-service[1505]: Invoked with name=named pattern=None enabled=True state=restarted sleep=None arguments= runlevel=default
Mar 16 15:51:36 schoolserver.lan systemd[1]: Reloading.
Mar 16 15:51:36 schoolserver.lan systemd[1]: Stopped Berkeley Internet Name Domain (DNS).
Mar 16 15:51:37 schoolserver.lan systemd[1]: Starting Generate rndc key for BIND (DNS)...
Mar 16 15:51:37 schoolserver.lan systemd[1]: Starting Network Manager Wait Online...
Mar 16 15:51:37 schoolserver.lan generate-rndc-key.sh[1528]: Generating /etc/rndc.key:[  OK  ]
Mar 16 15:51:37 schoolserver.lan systemd[1]: Started Generate rndc key for BIND (DNS).
Mar 16 15:52:08 schoolserver.lan systemd[1]: NetworkManager-wait-online.service: main process exited, code=exited, status=1/FAILURE
Mar 16 15:52:08 schoolserver.lan systemd[1]: Failed to start Network Manager Wait Online.
Mar 16 15:52:08 schoolserver.lan systemd[1]: Unit NetworkManager-wait-online.service entered failed state.
Mar 16 15:52:08 schoolserver.lan systemd[1]: Starting Network is Online.
Mar 16 15:52:08 schoolserver.lan systemd[1]: Reached target Network is Online.
Mar 16 15:52:08 schoolserver.lan systemd[1]: Starting Berkeley Internet Name Domain (DNS)...
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone localhost.localdomain/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone localhost/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named-checkconf[1535]: zone 0.in-addr.arpa/IN: loaded serial 0
Mar 16 15:52:08 schoolserver.lan named[1539]: starting BIND 9.9.4-P2-RedHat-9.9.4-18.P2.fc20 -u named -4 -c /etc/named-xs.conf
Mar 16 15:52:08 schoolserver.lan named[1539]: built with '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr
Mar 16 15:52:08 schoolserver.lan named[1539]: ----------------------------------------------------
Mar 16 15:52:08 schoolserver.lan named[1539]: BIND 9 is maintained by Internet Systems Consortium,
Mar 16 15:52:08 schoolserver.lan named[1539]: Inc. (ISC), a non-profit 501(c)(3) public-benefit
Mar 16 15:52:08 schoolserver.lan named[1539]: corporation.  Support and training for BIND 9 are
Mar 16 15:52:08 schoolserver.lan named[1539]: available at https://www.isc.org/support
Mar 16 15:52:08 schoolserver.lan named[1539]: ----------------------------------------------------
Mar 16 15:52:08 schoolserver.lan named[1539]: adjusted limit on open files from 4096 to 1048576
Mar 16 15:52:08 schoolserver.lan named[1539]: found 1 CPU, using 1 worker thread
Mar 16 15:52:08 schoolserver.lan named[1539]: using 1 UDP listener per interface
Mar 16 15:52:08 schoolserver.lan named[1539]: using up to 4096 sockets
Mar 16 15:52:08 schoolserver.lan named[1539]: loading configuration from '/etc/named-xs.conf'
Mar 16 15:52:08 schoolserver.lan named[1539]: /etc/named-xs.conf:57: open: /var/named-xs/named.root.hints: permission denied
Mar 16 15:52:08 schoolserver.lan named[1539]: loading configuration: permission denied
Mar 16 15:52:08 schoolserver.lan named[1539]: exiting (due to fatal error)
Mar 16 15:52:08 schoolserver.lan systemd[1]: named.service: control process exited, code=exited status=1
Mar 16 15:52:08 schoolserver.lan systemd[1]: Failed to start Berkeley Internet Name Domain (DNS).
Mar 16 15:52:08 schoolserver.lan systemd[1]: Unit named.service entered failed state.

[root@localhost xsce]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: p2p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:2e:35:80 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.42/24 brd 192.168.0.255 scope global dynamic p2p1
       valid_lft 84792sec preferred_lft 84792sec
    inet6 fe80::a00:27ff:fe2e:3580/64 scope link
       valid_lft forever preferred_lft forever
3: p7p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:13:68:ff brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe13:68ff/64 scope link
       valid_lft forever preferred_lft forever

**Comment by tim-moody** [comment]
in case this is relevant

[root@localhost xsce]# ll /var/named-xs/
total 64
drwxr-xr-x. 2 named root 4096 Mar 16 15:51 data
-rwxr-xr-x. 1 named root  198 Mar 16 15:51 localdomain.zone
-rwxr-xr-x. 1 named root  195 Mar 16 15:51 localhost.zone
-rwxr-xr-x. 1 named root  427 Mar 16 15:51 named.broadcast
-rwxr-xr-x. 1 named root  424 Mar 16 15:51 named.ip6.local
-rwxr-xr-x. 1 named root  426 Mar 16 15:51 named.local
-rwxr-xr-x. 1 named root  907 Mar 16 15:51 named.rfc1912.zones
-rwxr-xr-x. 1 named root 3048 Mar 16 15:51 named.root
-rwxr-xr-x. 1 named root  524 Mar 16 15:51 named.root.hints
-rwxr-xr-x. 1 named root  427 Mar 16 15:51 named.zero
-rwxr-xr-x. 1 named root  336 Mar 16 15:51 school.external.zone.db
-rw-r--r--. 1 named root   79 Mar 16 15:51 school.internal.zone.16.in-addr.db
-rw-r--r--. 1 named root   79 Mar 16 15:51 school.internal.zone.32.in-addr.db
-rw-r--r--. 1 named root   79 Mar 16 15:51 school.internal.zone.48.in-addr.db
-rwxr-xr-x. 1 root  root  539 Mar 16 15:51 school.internal.zone.db
-rw-r--r--. 1 named root   79 Mar 16 15:51 school.internal.zone.in-addr.db

**Comment by tim-moody** [comment]
-rwxr-xr-x. 1 root root 539 Mar 16 15:51 school.internal.zone.db ?

**Comment by jvonau** [comment]
Think this version of named is balking at the 0755 mode on some the files,
think those should be 0644

**Comment by jvonau** [comment]
Mar 16 15:52:08 schoolserver.lan named[1539]: /etc/named-xs.conf:57: open:
/var/named-xs/named.root.hints: permission denied

**Comment by jvonau** [comment]
I pushed a commit to set the perms to 0644 for named, think that should fix
it. I'm not sure what the impact of the "Failed to start Network Manager
Wait Online." would be. There maybe a delay during the first run of named
that ansible doesn't like.

**Comment by tim-moody** [comment]
nope, still get 

[root@localhost xsce]# journalctl -xn
-- Logs begin at Tue 2014-07-01 11:08:44 EDT, end at Mon 2015-03-16 20:51:31 EDT. --
Mar 16 20:51:31 schoolserver.lan named[11122]: found 1 CPU, using 1 worker thread
Mar 16 20:51:31 schoolserver.lan named[11122]: using 1 UDP listener per interface
Mar 16 20:51:31 schoolserver.lan named[11122]: using up to 4096 sockets
Mar 16 20:51:31 schoolserver.lan named[11122]: loading configuration from '/etc/named-xs.conf'
Mar 16 20:51:31 schoolserver.lan named[11122]: /etc/named-xs.conf:57: open: /var/named-xs/named.root.hints: permission denied
Mar 16 20:51:31 schoolserver.lan named[11122]: loading configuration: permission denied
Mar 16 20:51:31 schoolserver.lan named[11122]: exiting (due to fatal error)
Mar 16 20:51:31 schoolserver.lan systemd[1]: named.service: control process exited, code=exited status=1
Mar 16 20:51:31 schoolserver.lan systemd[1]: Failed to start Berkeley Internet Name Domain (DNS).
-- Subject: Unit named.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit named.service has failed.
--
-- The result is failed.
Mar 16 20:51:31 schoolserver.lan systemd[1]: Unit named.service entered failed state.

**Comment by tim-moody** [comment]
on a working system I have

[root@xsce-devel html]# ll /var/named-xs
total 64
drwxr-xr-x. 2 named root 4096 Jan 20 11:28 data
-rwxr-xr-x. 1 named root  198 Jan 20 11:28 localdomain.zone
-rwxr-xr-x. 1 named root  195 Jan 20 11:28 localhost.zone
-rwxr-xr-x. 1 named root  427 Jan 20 11:28 named.broadcast
-rwxr-xr-x. 1 named root  424 Jan 20 11:28 named.ip6.local
-rwxr-xr-x. 1 named root  426 Jan 20 11:28 named.local
-rwxr-xr-x. 1 named root  907 Jan 20 11:28 named.rfc1912.zones
-rwxr-xr-x. 1 named root 3048 Jan 20 11:28 named.root
-rwxr-xr-x. 1 named root  524 Jan 20 11:28 named.root.hints
-rwxr-xr-x. 1 named root  427 Jan 20 11:28 named.zero
-rwxr-xr-x. 1 named root  336 Jan 20 11:28 school.external.zone.db
-rw-r--r--. 1 named root   79 Jan 20 11:28 school.internal.zone.16.in-addr.db
-rw-r--r--. 1 named root   79 Jan 20 11:28 school.internal.zone.32.in-addr.db
-rw-r--r--. 1 named root   79 Jan 20 11:28 school.internal.zone.48.in-addr.db
-rwxr-xr-x. 1 root  root  539 Jan 20 11:28 school.internal.zone.db
-rw-r--r--. 1 named root   79 Jan 20 11:28 school.internal.zone.in-addr.db

**Comment by jvonau** [comment]
It's SElinux, see latest commit

**Comment by tim-moody** [comment]
selinux is supposed to be handled in 2-common/selinux.yml

this has worked until now

**Comment by tim-moody** [comment]
by putting network in 2-common/meta it now runs first, before selinux
it used to be in 3-base after everything in 2

**Comment by jvonau** [comment]
Need to move that to 1-prep to catch the gateway installs that now run from
meta, before selinux.yml is..    one moment please...

**Comment by tim-moody** [comment]
or don't put it in meta

**Comment by jvonau** [comment]
I didn't catch this one as I usually already have selinux disabled when
running ansible for the first time. Moved selinux to 1-prep allows install
to continue when install started in selinux enforcing mode.

**Comment by tim-moody** [comment]
moving network back to 3 would do the same thing.
what's the reason to move these things around?

**Comment by jvonau** [comment]
In order to support static ip addresses the network needs to be brought up earlier than the first network access with yum so I moved network to be run before 2-common. Didn't notice the selinux issue as it was already disabled before I started the install.

I tried to be proactive with avahi, between F18<>F21 the naming of the docs directory changed from <package>-<version> to <package>, but got burnt with avahi-libs that was added in between. a260633

Ran into a real slow down in internet access when installing in gateway mode, tracked it down to wondershaper. I don't think that should be enabled by default until the included values can be better accessed.  a4046b3

**Comment by tim-moody** [comment]
I was expecting that the wan would always come up as dhcp initially.  That is still the default, right?

Afterwards someone can change to static either using the console or local_var?  Can they lock themselves out?

Is it possible subsequently to go back to dhcp using the console or local_var?

**Comment by tim-moody** [comment]
what is the relationship between these?

wan_ip: dhcp
user_wan_iface: auto

1st is to override ip and second to override nic?

**Comment by tim-moody** [comment]
on x64 vm smoke test with all three roles worked

**Comment by tim-moody** [comment]
tried (stupidly was ssh'd in when I ran it, so lost connection)
wan_ip: 192.168.0.195
wan_netmask: 255.255.255.0
wan_gateway: 192.168.0.1
wan_nameserver: 192.168.0.1
user_wan_iface: auto

was subsequently able to login at 192.168.0.195, but log shows possible problem

2015-03-17 11:45:31,214 p=11249 u=root |  TASK: [network | debug msg="hopefully now NM is restarted"] *******************
2015-03-17 11:45:31,256 p=11249 u=root |  ok: [127.0.0.1] => {
    "msg": "hopefully now NM is restarted"
}
2015-03-17 11:45:31,257 p=11249 u=root |  TASK: [network | use upstream nameserver until named is installed] ************
2015-03-17 11:45:31,639 p=11249 u=root |  failed: [127.0.0.1] => {"failed": true}
2015-03-17 11:45:31,643 p=11249 u=root |  msg: unsupported parameter for module: follow
2015-03-17 11:45:31,646 p=11249 u=root |  FATAL: all hosts have already failed -- aborting
2015-03-17 11:45:31,647 p=11249 u=root |  PLAY RECAP ********************************************************************
2015-03-17 11:45:31,652 p=11249 u=root |             to retry, use: --limit @/root/xsce-base.retry

2015-03-17 11:45:31,652 p=11249 u=root |  127.0.0.1                  : ok=43   changed=6    unreachable=0    failed=1

**Comment by tim-moody** [comment]
local_vars

#intended for developers
#wan_ip: 192.168.0.195
#wan_netmask: 255.255.255.0
#wan_gateway: 192.168.0.1
#wan_nameserver: 192.168.0.1
user_wan_iface: auto

./install-console, wan ip did not go back to dhcp

**Comment by jvonau** [comment]
Yea I know, you entered expert mode use at own risk. Pushed fix for the
"follow" issue, bit of a late night thinkO on my part, pushed to the wrong
branch in my git, you tested that before I did, sorry. Deleting the ifcfg
file should put you back to dhcp.

During our conversation it was decided:

1.  that the routine should not delete a user's file
2.  that WAN should not have an ifcfg file when using dhcp
3.  we should not supply a file if using dhcp.

To be able to move back to dhcp one would need to remove the ifcfg file,
but we couldn't tell who supplied this file. Now that "Generated by XSCE"
is added to files we supply, that string can now be used to determine if
the routine supplied this file before removal. I was buliding up to use
that in the future here and in bridge clean up.

The other alternative is alter the ifcfg file for use with dhcp, the
template already has that info defined but is currently unused. I like this
one better as we really should be ignoring the isp's nameservers once we
have our dns server active.

Otherwise you end up with the WAN's namesevers listed in resolv.conf, if
those entries appear above 127.0.0.1 then lookups might go upstream before
trying the local server. That can lead to some strange behavior when
resolving on the server itself for things that use {xsce_domain}. I would
prefer not to give the lookups a choice in which nameserver to use. I will
go with the flow until this issue pops up somewhere, leading to some weird
behavior that is hard to track down.

I'll add the test to remove based on the "XSCE" string if needed right now,
or just wait for a bit as this is optional user initiated behavior that you
will not hit in a stock non-expert install?

**Comment by tim-moody** [comment]
Are we providing a nameserver on wan?

>
>From: Jerry Vonau 
>Sent: Tuesday, March 17, 2015 2:17 PM
>To: XSCE/xsce 
>Cc: Tim Moody 
>Subject: Re: [xsce] Merge gateway into Network (#239)
>
>Yea I know, you entered expert mode use at own risk. Pushed fix for the
>"follow" issue, bit of a late night thinkO on my part, pushed to the wrong
>branch in my git, you tested that before I did, sorry. Deleting the ifcfg
>file should put you back to dhcp.
>
>During our conversation it was decided:
>
>1. that the routine should not delete a user's file
>2. that WAN should not have an ifcfg file when using dhcp
>3. we should not supply a file if using dhcp.
>
>To be able to move back to dhcp one would need to remove the ifcfg file,
>but we couldn't tell who supplied this file. Now that "Generated by XSCE"
>is added to files we supply, that string can now be used to determine if
>the routine supplied this file before removal. I was buliding up to use
>that in the future here and in bridge clean up.
>
>The other alternative is alter the ifcfg file for use with dhcp, the
>template already has that info defined but is currently unused. I like this
>one better as we really should be ignoring the isp's nameservers once we
>have our dns server active.
>
>Otherwise you end up with the WAN's namesevers listed in resolv.conf, if
>those entries appear above 127.0.0.1 then lookups might go upstream before
>trying the local server. That can lead to some strange behavior when
>resolving on the server itself for things that use {xsce_domain}. I would
>prefer not to give the lookups a choice in which nameserver to use. I will
>go with the flow until this issue pops up somewhere, leading to some weird
>behavior that is hard to track down.
>
>I'll add the test to remove based on the "XSCE" string if needed right now,
>or just wait for a bit as this is optional user initiated behavior that you
>will not hit in a stock non-expert install?
>
>
>On Tue, Mar 17, 2015 at 11:51 AM, Tim Moody <notifications@github.com>
>wrote:
>
>> local_vars
>>
>> #intended for developers
>> #wan_ip: 192.168.0.195
>> #wan_netmask: 255.255.255.0
>> #wan_gateway: 192.168.0.1
>> #wan_nameserver: 192.168.0.1
>> user_wan_iface: auto
>>
>> ./install-console, wan ip did not go back to dhcp
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/XSCE/xsce/pull/239#issuecomment-82474343>.
>>
>
>—
>Reply to this email directly or view it on GitHub.
>

-- 
Sig inserted by AutoHotkey ver. 1.1.11.01 (signature - first line)
WLMail QuoteFix -> http://www.dusko-lolic.from.hr/ (signature - second line)

**Comment by jvonau** [comment]
Named always did listen on the wan interface but we are blocking access
with iptables, so effectively no. The external view would need additional
work to make name resolution from the wan effective, that is really
inherited crud that should just be removed, just not right now.

The only time we need to use upstream dns is when we don't have named setup
yet, using the upstream dns would just be a crutch to bootstrap the
installing of named. Once named is active it is the authoritative dns
server for ".lan" and should be consulted first before other dns servers
are tried for the ".lan" domain.

**Pull request merged**
