### PR TITLE
Reconcile install

### PR DESCRIPTION
**Pull request by tim-moody**
create install-init script and playbook to set up var files before subsequent scripts
call install-init at the beginning of runansbile, runtags, and install-console
change top level playbooks to use local_vars from /etc/xsce
change top level playbooks to add config_vars from /etc/xsce
fix a few syntax errors in comments
remove some trailing blanks

### CODE REVIEW

**Comment by georgejhunt** [comment]
So as I understand it, once a user has run any config from the console, he
needs to copy /etc/xsce/console.yml to /etc/xsce/local_vars.yml, before he
does ./runtags, or ./runansible.

If that is so, maybe we need an easy to remember script name like
"revert_to_commandline" which does "cp /etc/xsce/console_vars.yml
/etc/xsce/local_vars.yml". Or maybe we just initialize /etc/xsce/local_vars
with what console_vars.yml is currently initialized with. Then as users, we
can look at a cmdline/console variable which we can check to see who is in
command.

Probably I don't understand enough. Let's talk on Saturday, at Adam's 10am
EDT meeting.

Or maybe  there's a reminder in runtags (I'm thinking of the "./runtags
network" situation) which checks a flag to see whether console config has
ever been run (I think in the old situation, console_vars.yml did not
exists until console config had occurred).

Until the console is more complete, there will always be things that can
only be done at the command line. We'll need some way, doing remote
administration without a GUI, to tweak things without destroying the
integrity of the console displayed data.

**Comment by tim-moody** [comment]
No; not any more.  Config_vars is now included in all the scripts, so there is no reason to copy anything.  But if you want to set a value, you should use the console, even if you like running runtags manually.

 

Things that the console does not configure can still be configured with local vars, but config vars wins over local vars for things that can be set either place, because the reverse will confuse gui users.

 

 

So as I understand it, once a user has run any config from the console, he
needs to copy /etc/xsce/console.yml to /etc/xsce/local_vars.yml, before he
does ./runtags, or ./runansible.

Or maybe there's a reminder in runtags (I'm thinking of the "./runtags
network" situation) which checks a flag to see whether console config has
ever been run (I think in the old situation, console_vars.yml did not
exists until console config had occurred).

 

yes, but now it does.

Until the console is more complete, there will always be things that can
only be done at the command line. We'll need some way, doing remote
administration without a GUI, to tweak things without destroying the
integrity of the console displayed data.

**Comment by georgejhunt** [comment]
Could we eliminate local_vars.yml? And always just use config_vars.yml?
Then we would not need to even think about whether console knows about it
or not.

**Comment by tim-moody** [comment]
I take it you mean having the console edit a file that can also be edited with a text editor.  I thought about this, but it is harder than it might seem.  If you read a yml file in python you lose all the comments.   There is a ruamel library, but it converts lines into a special object, so that they are no longer lists or dicts and so harder to work with.  Also, if someone messes up a line the console will be broken.  There needs to be a home for things like password hashes that are not yet or possibly ever handled in the console, things that might span installs like the country level xsce-admin password.

**Comment by georgejhunt** [comment]
Or just always automatically append/replace console_config.yml to the end
of local_vars, such that it always overrides local_vars, and is visible to
cmdline folks who are wondering why their changes are not honored (or get
overridden by GUI user tomorrow, or next year).

I'm only trying for consistent, understandable behavior.

**Pull request merged**
