### PR TITLE
Nm fix

### PR DESCRIPTION
**Pull request by georgejhunt**
Found these changes necessary for install of master on XO4

### CODE REVIEW

**Comment by tim-moody** [comment]
On an XO-4:

-bash-4.2# cat  /usr/lib/systemd/system/NetworkManager-dispatcher.service
[Unit]
Description=Network Manager Script Dispatcher Service

[Service]
Type=dbus
BusName=org.freedesktop.nm_dispatcher
ExecStart=/usr/libexec/nm-dispatcher.action

[Install]
WantedBy=multi-user.target
Alias=dbus-org.freedesktop.nm-dispatcher.service


-bash-4.2# rpm -ql NetworkManager
/etc/NetworkManager
/etc/NetworkManager/NetworkManager.conf
/etc/NetworkManager/VPN
/etc/NetworkManager/dispatcher.d
/etc/NetworkManager/dnsmasq.d
/etc/NetworkManager/system-connections
/etc/dbus-1/system.d/nm-avahi-autoipd.conf
/etc/dbus-1/system.d/nm-dhcp-client.conf
/etc/dbus-1/system.d/nm-dispatcher.conf
/etc/dbus-1/system.d/nm-ifcfg-rh.conf
/etc/dbus-1/system.d/org.freedesktop.NetworkManager.conf
/lib/udev/rules.d/77-nm-olpc-mesh.rules
/usr/bin/nm-online
/usr/bin/nm-tool
/usr/bin/nmcli
/usr/lib/NetworkManager
/usr/lib/NetworkManager/libnm-settings-plugin-ifcfg-rh.so
/usr/lib/pppd/2.4.5/nm-pppd-plugin.so
/usr/lib/systemd/system/NetworkManager-dispatcher.service
/usr/lib/systemd/system/NetworkManager-wait-online.service
/usr/lib/systemd/system/NetworkManager.service
/usr/lib/systemd/system/network-online.target.wants/NetworkManager-wait-online.service
/usr/libexec/nm-avahi-autoipd.action
/usr/libexec/nm-dhcp-client.action
/usr/libexec/nm-dispatcher.action
/usr/sbin/NetworkManager
/usr/share/bash-completion/completions/nmcli
/usr/share/dbus-1/system-services/org.freedesktop.NetworkManager.service
/usr/share/dbus-1/system-services/org.freedesktop.nm_dispatcher.service
/usr/share/doc/NetworkManager-0.9.8.2
/usr/share/doc/NetworkManager-0.9.8.2/AUTHORS
/usr/share/doc/NetworkManager-0.9.8.2/CONTRIBUTING
/usr/share/doc/NetworkManager-0.9.8.2/COPYING
/usr/share/doc/NetworkManager-0.9.8.2/NEWS
/usr/share/doc/NetworkManager-0.9.8.2/README
/usr/share/doc/NetworkManager-0.9.8.2/TODO
/usr/share/locale/ar/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/as/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/be@latin/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/bg/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/bn_IN/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/bs/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ca/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/cs/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/da/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/de/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/dz/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/el/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/en_CA/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/en_GB/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/eo/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/es/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/et/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/eu/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/fi/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/fr/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/gl/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/gu/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/he/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/hi/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/hr/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/hu/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/id/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/it/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ja/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ka/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/kn/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ko/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ku/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/lt/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/lv/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/mk/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ml/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/mr/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/nb/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ne/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/nl/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/oc/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/or/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/pa/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/pl/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/pt/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/pt_BR/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ru/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/rw/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sk/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sl/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sq/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sr/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sr@latin/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/sv/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/ta/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/te/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/th/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/tr/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/uk/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/vi/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/wa/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/zh_CN/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/zh_HK/LC_MESSAGES/NetworkManager.mo
/usr/share/locale/zh_TW/LC_MESSAGES/NetworkManager.mo
/usr/share/man/man1/nm-online.1.gz
/usr/share/man/man1/nm-tool.1.gz
/usr/share/man/man1/nmcli.1.gz
/usr/share/man/man5/NetworkManager.conf.5.gz
/usr/share/man/man5/nm-system-settings.conf.5.gz
/usr/share/man/man8/NetworkManager.8.gz
/usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy
/var/lib/NetworkManager
-bash-4.2#

**Comment by georgejhunt** [comment]
NM references removed. Still think the expansion of /tmp is necessary

**Comment by jvonau** [comment]
This may not be required now on master. In PR #248 I noted: "The stock location is /tmp/pear/download." This is now set: see: https://github.com/XSCE/xsce/commit/61bb8bbebafb19c3821fc682672c1c3e57de3caa

**Comment by georgejhunt** [comment]
I reran master on a clean install of ...13.2.1. Is it possible that you
were using 13.2.2?

My rpm -qil NetworkManager did not have systemd NetworkManager-dispatcher

My NM --version was0.9.8.1-3.git 201131514. I guess I chose 13.2.1, because
I don't think James created an image for i686.

Maybe we need to test on XO1.5 to decide.

**Comment by georgejhunt** [comment]
I did yum update NetworkManager, and the resultant update had
NetworkManager-dispatcher and was version 0.9.8.2-1.fc18. So maybe the fix
is to add NetworkManager to the list of updates.

**Comment by tim-moody** [comment]
guilty:

 

-bash-4.2# uname -a

Linux schoolserver.lan 3.5.7_xo4-20141118.2329.olpc.cd558cf #1 PREEMPT Tue Nov 18 23:41:33 GMT 2014 armv7l armv7l armv7l GNU/Linux

 

But this always used to work with 32013o4.zd

**Comment by georgejhunt** [comment]
The XO4 on stock 13.2.1 ran to completion with the /tmp reset to 100M and
the upgrade to newer NetworkManager.   I propose that we merge this PR even
though Jerry thinks it might not be needed. I read that tmpfs is not memory
allocated until it is needed.

**Comment by jvonau** [comment]
Question becomes why didn't NM update when we ask for that in yum.yml...

**Comment by tim-moody** [comment]
I am unable to do an install on stock xo4 without adding an sd card as it no longer fits in 4G. I put in an 8G card with 2G for /opt and 6G for /library.  The whole xo4 thing keeps getting more exotic.

**Comment by georgejhunt** [comment]
I'll need to do another clean install, and look specifically at the yum.yml
part of the log

**Comment by tim-moody** [comment]
The version of anisble could also be involved.  I have 1.4.1 on xo4.

 

Also, if you change a condition from == XO to != XO then all platforms must be tested, not just XO.

 

If you only want to change /tmp, then you should remove the NM part of the PR.

**Comment by jvonau** [comment]
PR #259 bumps /tmp  and is merged, PR #260 address the NM issue.

**Pull request closed without merging**
