### PR TITLE
hyphen vs underbar in kiwix_serve_enabled

### PR DESCRIPTION
**Pull request by georgejhunt**
The service is named kiwix-serve but the variable is kiwix_serve_enabled (I think)

### CODE REVIEW

**Comment by tim-moody** [comment]
why is this issue coming up again?  is there a problem with the name kiwix-serve_enabled?  our convention is to use _enabled.  the name of the kiwix service from kiwix is kiwix-serve.  I thought Jerry and I already had this discussion.  It maybe true that there is another role with a _serve flag, don't remember which, but unless there is a parse error with this name I think kiwix-serve_enabled is the right name.

Date: Thu, 30 Apr 2015 20:37:06 -0700

**Comment by jvonau** [comment]
"kiwix-serve_enabled" results in a parsing error.

**Comment by jvonau** [comment]
TASK: [kiwix | Get the kiwix software] ****************************************
skipping: [127.0.0.1]

TASK: [kiwix | Create various directories for zims] ***************************
ok: [127.0.0.1] => (item=/library/zims)
ok: [127.0.0.1] => (item=/library/zims/content)
ok: [127.0.0.1] => (item=/library/zims/index)
ok: [127.0.0.1] => (item=/library/downloads/zims)

TASK: [kiwix | Unarchive it to permanent location - not bin_only] *************
skipping: [127.0.0.1]

TASK: [kiwix | Create directory for kiwix bin] ********************************
ok: [127.0.0.1]

TASK: [kiwix | Unarchive it to permanent location - bin only] *****************
changed: [127.0.0.1]

TASK: [kiwix | Set kiwix ownership] *******************************************
changed: [127.0.0.1]

TASK: [kiwix | Create kiwix library file] *************************************
changed: [127.0.0.1]

TASK: [kiwix | Create kiwix-serve service] ************************************
ok: [127.0.0.1] => (item={'dest': '/etc/systemd/system/kiwix-serve.service', 'src': 'kiwix-serve.service.j2', 'mode': '0655'})

TASK: [kiwix | add kiwix to service list] *************************************
fatal: [127.0.0.1] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 394, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 460, in _executor_internal
    items_terms = template.template(basedir, items_terms, inject)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 343, in template
    return [template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined) for v in varname]
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 347, in template
    d[k] = template(basedir, v, vars, lookup_fatal, depth, expand_lists, fail_on_undefined=fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 319, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/utils/template.py", line 541, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
TypeError: unsupported operand type(s) for -: 'StrictUndefined' and 'StrictUndefined'

**Comment by georgejhunt** [comment]
I've changed my PR to include a change to line 81 of
roles/kiwix/tasks/kiwix_install.yml.

So I think this error is addressed. But I have not tested it on a clean
install

**Comment by tim-moody** [comment]
Thanks, all I needed to know. Sent from my BlackBerry® PlayBook™www.blackberry.comFrom: "Jerry Vonau" <notifications@github.com>To: "XSCE/xsce" <xsce@noreply.github.com>CC: "Tim Moody" <tim@timmoody.com>Sent: 1 May, 2015 6:46 AMSubject: Re: [xsce] hyphen vs underbar in kiwix_serve_enabled (#311) "kiwix-serve_enabled" results in a parsing error.

**Comment by georgejhunt** [comment]
I hope this is right. In our skype today, Jerry recounted his experience with another situation where jinga2 did not parse ini files with "-" in the text.

**Pull request merged**
