### PR TITLE
RFC -- these are the Raspberry Pi 2 networking changes

### PR DESCRIPTION
**Pull request by georgejhunt**
Assignment of adapters works differently now:
  1. look for wifi, and gateway
  2. count the number of adapters that are not wifi and not gateway
  3.  if wifi plus this number > 1, create a bridge, and connect slaves to bridge
If hostapd/wifi/bridge is involved, enable network.service as well as NM.
Add and subtract lines in /etc/rc.d/rc.local to attach adapters to bridge.
Add a hw-detect yml file

### CODE REVIEW

**Comment by jvonau** [comment]
Have you tried running this branch on a non-rpi2?

**Comment by georgejhunt** [comment]
Not yet I was trying to get all the transitions to work, before it did that

**Comment by jvonau** [comment]
Have a look at nonNM-bridging.ym in PR #230, I had this working with F18 but for some reason I was led to believe that network.service was not wanted.

**Comment by tim-moody** [comment]
superceded by 268

**Pull request closed without merging**
