### PR TITLE
CentOS

### PR DESCRIPTION
**Pull request by jvonau**
Base on #166 
runs ./install-console to completion

### CODE REVIEW

**Comment by georgejhunt** [comment]
I have some additional commits which got me through the full runansible,
which installs everything, but does not enable most. -- it's what Tony is
playing with.  But my current version does not merge with master.

I propose that you put your stuff in master, and then I can create a PR
against what's in master.

**Comment by jvonau** [comment]
Yea I stopped at install-console, what other playbooks did you disable?

**Comment by tim-moody** [comment]
any implication for mysql vs mariadb package name calc?

From: Jerry Vonau 
Sent: Tuesday, March 24, 2015 9:11 AM
To: XSCE/xsce 
Subject: [xsce] CentOS (#247)

Base on #166 
runs ./install-console to completion 


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/XSCE/xsce/pull/247

Commit Summary
  a.. add in the Centos repos 
  b.. forgot the new files 
  c.. put a centos.repo for recompiled rpsm 
  d.. enable the epel-testing repo 
  e.. disable gpg checksum on epel-testing 
  f.. use upstream repo files 
  g.. merging master 
  h.. remove upstream repo files 
  i.. split out fedora specific rpms 
  j.. forgot the tag 
  k.. better title 
File Changes
  a.. A roles/1-prep/tasks/centos.yml (13) 
  b.. M roles/1-prep/tasks/main.yml (5) 
  c.. A roles/1-prep/templates/xsce-centos.repo (7) 
  d.. A roles/2-common/tasks/fedora.yml (6) 
  e.. M roles/2-common/tasks/main.yml (5) 
  f.. M roles/2-common/tasks/yum.yml (2) 
Patch Links:
  a.. https://github.com/XSCE/xsce/pull/247.patch 
  b.. https://github.com/XSCE/xsce/pull/247.diff

**Comment by georgejhunt** [comment]
PR166 still is updated to the things I had to do for Tony.  As I look
through, I see

disable sugar-stats, and xo-vis

There was also some name conflict with idmgr in the Centos7 build in the
/usr/libexec folder, so I needed to creeate xs-idmgr ,

centos does not have mysql-server, but fc18 does not have mariadb-server,
so I made it variable

make one additional directory /etc/usbmount/mound.d

Otherwise I think you got it. I like using epel-release rather than
templates, I was just shortcutting.

**Comment by jvonau** [comment]
now ./install-console and ./runtags mysql runs to completion.

**Comment by jvonau** [comment]
xovis installs, forced "sugar-stats_install: False" as that fails

**Comment by jvonau** [comment]
./runansible runs to completion

**Comment by georgejhunt** [comment]
The Centos image I gave to Tony was defective in that a last minute change
I made to grab /library into a separate tar file(tar does not appear to
cross filesystems easily) caused that tar to be missing in the online image.

So I used Jerry's PR, on a new clean Centos7.  Worked fine. And all of the
latest stuff in master got included! Great work.

**Pull request merged**
