### PR TITLE
Ansible2

### PR DESCRIPTION
**Pull request by georgejhunt**
These changes permit ansible 2.0 to run on current CentOS

### CODE REVIEW

**Comment by tim-moody** [comment]
I prefer the settings style of coding to the tags.  You left out the try for tags if ansible >=2

**Comment by georgejhunt** [comment]
I do not understand settings vs tags, and where this might apply. An example would help.  

Are the changes I made to xsce-cmdsrv acceptable to you?

**Comment by georgejhunt** [comment]
Thinking about it more, maybe you meant that you prefer the playbook approach:
-name: Get the ansible version
  shell: "ansible --version | head -n1 | cut -d' ' -f2"  
  register: version_response

-name set version fact
 set_fact: ansible_version={{version_response.stdout}}

rather than local fact library approach

**Comment by tim-moody** [comment]
in cmdsrv I like the approach of 1635ff better than 1646ff.

**Comment by georgejhunt** [comment]
Ok, now I think I understand.  I'll fix

**Pull request merged**
