### PR TITLE
put the partitioning in for ssd card

### PR DESCRIPTION
**Pull request by georgejhunt**
The only actual changes to demo.ks are the three "part" lines after clearpart

### CODE REVIEW

**Comment by jvonau** [comment]
This looks to be MBR specific with the use of /boot how does this behave under UEFI?''

**Comment by georgejhunt** [comment]
Good point.

My objective is to create an install process that is automatic.  If you see
a way to detect, and accommodate bios settings, that would be ideal. I have
not done a UEFI anaconda run, and don't know the appropriate settings.

Otherwise, I think it is time to start closing off options, and making the
install something that Adam can use to create the first 10 SSD NUCs.

**Comment by tim-moody** [comment]
I did a UEFI install on my nuc.  I favor doing that exclusively. here is the anaconda-ks.cfg file:

[root@localhost ~]# cat anaconda-ks.cfg
#version=DEVEL
# System authorization information
auth --enableshadow --passalgo=sha512
# Use CDROM installation media
cdrom
# Use graphical install
graphical
# Run the Setup Agent on first boot
firstboot --enable
ignoredisk --only-use=sda
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=eno1 --ipv6=auto --activate
network  --hostname=localhost.localdomain

# Root password
rootpw --iscrypted $6$W7b9pi4iNDYx/DaQ$OSdLiRyGUAl3uLdQw4x94ueH30vQAV68OLqJyBo/43h5U9vyzn/oQYkz.YxeCMtoMMteAKcpR/bsCYhsQC/Qk1
# System timezone
timezone America/New_York --isUtc
# System bootloader configuration
bootloader --append=" crashkernel=auto" --location=mbr --boot-drive=sda
# Partition clearing information
clearpart --none --initlabel
# Disk partitioning information
part / --fstype="ext4" --ondisk=sda --size=113772
part /boot --fstype="xfs" --ondisk=sda --size=500
part /boot/efi --fstype="efi" --ondisk=sda --size=200 --fsoptions="umask=0077,shortname=winnt"

%packages
@^minimal
@core
kexec-tools

%end

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

**Comment by tim-moody** [comment]
no; I don't understand your point.  are you saying partitioning is different for mbr than uefi?  yes that's true.  I think we should select just one and it should be uefi.

Date: Tue, 12 Jul 2016 09:30:41 -0700

**Pull request closed without merging**
