### PR TITLE
RFC - FYI tracking jv's installer4 branch

### PR DESCRIPTION
**Pull request by jvonau**
This is based off of #266 and is not meant to merged. This is more of a heads up, tracking work in progress.

### CODE REVIEW

**Comment by georgejhunt** [comment]
On the call this week, did we agree that there would be ini entries for xsce_hw and xsce_distro?
I should take notes, because this doesn't seem exactly right.

**Comment by jvonau** [comment]
Think we did, the xsce_distro is straight forward, for xsce_hw should that be based on arch(arm,i686,x86_64) then sub-classified variant such as the Rpi?

**Comment by georgejhunt** [comment]
ansible presents a processor id. But for rpi it is not as diagnostic when
recognizing rpi2 as the ansible_cmdline entry bcm2709.serial (cpu is
broadcom 2709 which identifies the IO address for communicating with
console). So I think we are going to have to look at what ansible returns,
and maybe do some bash stuff to identify as much as we can about the
hardware we are running on.

And I'd like a place to put that information. To be consistent with our
naming -- xsce_discovered_hardware? or xsce_discovered_hw

Maybe there are better options...

**Comment by jvonau** [comment]
George can you please toss a copy of the output of "ansible -m setup -i ansible_hosts localhost --connection=local" into PR #263, so we can see what you can see on the rpi2

**Comment by georgejhunt** [comment]
here it is:


127.0.0.1 | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "172.18.96.1",
            "192.168.123.144"
        ],
        "ansible_all_ipv6_addresses": [
            "fe80::ba27:ebff:fe23:249c",
            "fe80::daeb:97ff:febd:4aae",
            "fe80::ba27:ebff:fe23:249c",
            "fe80::eade:27ff:fea2:9577"
        ],
        "ansible_architecture": "armv7l",
        "ansible_bios_date": "NA",
        "ansible_bios_version": "NA",
        "ansible_br0": {
            "active": true,
            "device": "br0",
            "id": "8000.b827eb23249c",
            "interfaces": [
                "eth0",
                "eth1",
                "wlan0"
            ],
            "ipv4": {
                "address": "172.18.96.1",
                "netmask": "255.255.224.0",
                "network": "172.18.96.0"
            },
            "ipv6": [
                {
                    "address": "fe80::ba27:ebff:fe23:249c",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "b8:27:eb:23:24:9c",
            "mtu": 1500,
            "promisc": false,
            "stp": false,
            "type": "bridge"
        },
        "ansible_cmdline": {
            "bcm2708_fb.fbheight": "870",
            "bcm2708_fb.fbswap": "1",
            "bcm2708_fb.fbwidth": "1410",
            "bcm2709.boardrev": "0xa21041",
            "bcm2709.disk_led_active_low": "0",
            "bcm2709.disk_led_gpio": "47",
            "bcm2709.serial": "0x6223249c",
            "console": "tty1",
            "dma.dmachans": "0x7f35",
            "dwc_otg.lpm_enable": "0",
            "kgdboc": "ttyAMA0,115200",
            "ro": true,
            "root": "/dev/mmcblk0p3",
            "rootfstype": "ext4",
            "rootwait": true,
            "sdhci-bcm2708.emmc_clock_freq": "250000000",
            "slub_debug": "FP",
            "smsc95xx.macaddr": "B8:27:EB:23:24:9C",
            "vc_mem.mem_base": "0x3dc00000",
            "vc_mem.mem_size": "0x3f000000"
        },
        "ansible_date_time": {
            "date": "2015-04-04",
            "day": "04",
            "epoch": "1428194782",
            "hour": "20",
            "iso8601": "2015-04-05T00:46:22Z",
            "iso8601_micro": "2015-04-05T00:46:22.871874Z",
            "minute": "46",
            "month": "04",
            "second": "22",
            "time": "20:46:22",
            "tz": "EDT",
            "tz_offset": "-0400",
            "weekday": "Saturday",
            "year": "2015"
        },
        "ansible_default_ipv4": {
            "address": "192.168.123.144",
            "alias": "eth1",
            "gateway": "192.168.123.1",
            "interface": "eth1",
            "macaddress": "d8:eb:97:bd:4a:ae",
            "mtu": 1500,
            "netmask": "255.255.255.0",
            "network": "192.168.123.0",
            "type": "ether"
        },
        "ansible_default_ipv6": {},
        "ansible_devices": {
            "mmcblk0": {
                "holders": [],
                "host": "",
                "model": null,
                "partitions": {},
                "removable": "0",
                "rotational": "0",
                "scheduler_mode": "noop",
                "sectors": "62333952",
                "sectorsize": "512",
                "size": "29.72 GB",
                "support_discard": "4194304",
                "vendor": null
            }
        },
        "ansible_distribution": "Fedora",
        "ansible_distribution_major_version": "21",
        "ansible_distribution_release": "Twenty One",
        "ansible_distribution_version": "21",
        "ansible_domain": "lan",
        "ansible_env": {
            "COLORTERM": "xfce4-terminal",
            "DBUS_SESSION_BUS_ADDRESS":
"unix:abstract=/tmp/dbus-A4VLuzSwN7,guid=8c9e18633ac882a48123e95b551f7303",
            "DESKTOP_SESSION": "xfce",
            "DISPLAY": ":0.0",
            "GDMSESSION": "xfce",
            "GLADE_CATALOG_PATH": ":/usr/share/glade3/catalogs",
            "GLADE_MODULE_PATH": ":/usr/share/glade3/pixmaps",
            "GLADE_PIXMAP_PATH": ":/usr/lib/glade3/modules",
            "GNOME_KEYRING_CONTROL": "/root/.cache/keyring-EY9GWX",
            "GPG_AGENT_INFO": "/root/.gnupg/S.gpg-agent:2727:1",
            "HISTCONTROL": "ignoredups",
            "HISTSIZE": "1000",
            "HOME": "/root",
            "HOSTNAME": "schoolserver.lan",
            "IMSETTINGS_INTEGRATE_DESKTOP": "yes",
            "IMSETTINGS_MODULE": "none",
            "LANG": "C",
            "LC_CTYPE": "C",
            "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
            "LOGNAME": "root",
            "LS_COLORS":
"rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:",
            "MAIL": "/var/spool/mail/root",
            "PATH":
"/usr/local/sbin:/usr/sbin:/sbin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/root/bin",
            "PWD": "/opt/schoolserver/xsce",
            "QT_IM_MODULE": "xim",
            "SESSION_MANAGER": "local/unix:@
/tmp/.ICE-unix/2723,unix/unix:/tmp/.ICE-unix/2723",
            "SHELL": "/bin/bash",
            "SHLVL": "4",
            "SSH_AGENT_PID": "2706",
            "SSH_ASKPASS": "/usr/libexec/openssh/gnome-ssh-askpass",
            "SSH_AUTH_SOCK": "/tmp/ssh-soHahEyqAgyd/agent.2579",
            "TERM": "xterm-256color",
            "USER": "root",
            "WINDOWID": "50347471",
            "XAUTHORITY": "/var/run/lightdm/root/xauthority",
            "XDG_CONFIG_DIRS": "/etc/xdg",
            "XDG_DATA_DIRS": "/usr/local/share:/usr/share",
            "XDG_GREETER_DATA_DIR": "/var/lib/lightdm-data/root",
            "XDG_MENU_PREFIX": "xfce-",
            "XDG_RUNTIME_DIR": "/run/user/0",
            "XDG_SEAT": "seat0",
            "XDG_SEAT_PATH": "/org/freedesktop/DisplayManager/Seat0",
            "XDG_SESSION_ID": "c7",
            "XDG_SESSION_PATH": "/org/freedesktop/DisplayManager/Session0",
            "XDG_VTNR": "1",
            "XMODIFIERS": "@im=none",
            "_": "/usr/bin/python"
        },
        "ansible_eth0": {
            "active": true,
            "device": "eth0",
            "ipv6": [
                {
                    "address": "fe80::ba27:ebff:fe23:249c",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "b8:27:eb:23:24:9c",
            "module": "smsc95xx",
            "mtu": 1500,
            "promisc": true,
            "type": "ether"
        },
        "ansible_eth1": {
            "active": true,
            "device": "eth1",
            "ipv4": {
                "address": "192.168.123.144",
                "netmask": "255.255.255.0",
                "network": "192.168.123.0"
            },
            "ipv6": [
                {
                    "address": "fe80::daeb:97ff:febd:4aae",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "d8:eb:97:bd:4a:ae",
            "module": "asix",
            "mtu": 1500,
            "promisc": true,
            "type": "ether"
        },
        "ansible_fips": false,
        "ansible_form_factor": "NA",
        "ansible_fqdn": "schoolserver.lan",
        "ansible_hostname": "schoolserver",
        "ansible_interfaces": [
            "lo",
            "br0",
            "wlan0",
            "eth1",
            "eth0"
        ],
        "ansible_kernel":
"3.18.9-503.20150311git5e3fb83.sc20.armv7hl.bcm2709",
        "ansible_lo": {
            "active": true,
            "device": "lo",
            "ipv4": {
                "address": "127.0.0.1",
                "netmask": "255.0.0.0",
                "network": "127.0.0.0"
            },
            "ipv6": [
                {
                    "address": "::1",
                    "prefix": "128",
                    "scope": "host"
                }
            ],
            "mtu": 65536,
            "promisc": false,
            "type": "loopback"
        },
        "ansible_local": {
            "local_facts": {
                "phplib_dir": "/usr/lib/php",
                "xo_model": "none",
                "xsce_branch": "mypi",
                "xsce_commit": "6bdc818cf74e138163a3b774e206b8fca7db37e7"
            },
            "wondershaper": {
                "wondershaper": {
                    "dspeed": "4096",
                    "iface": "\"eth1\"",
                    "uspeed": "1024"
                }
            }
        },
        "ansible_machine": "armv7l",
        "ansible_memfree_mb": 73,
        "ansible_memtotal_mb": 863,
        "ansible_mounts": [
            {
                "device": "/dev/root",
                "fstype": "ext4",
                "mount": "/",
                "options": "rw,noatime,data=ordered",
                "size_available": 1739907072,
                "size_total": 8391680000
            },
            {
                "device": "/dev/mmcblk0p4",
                "fstype": "ext4",
                "mount": "/library",
                "options": "rw,noatime,data=ordered",
                "size_available": 79564800,
                "size_total": 475406336
            },
            {
                "device": "/dev/mmcblk0p1",
                "fstype": "vfat",
                "mount": "/boot",
                "options":
"rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro",
                "size_available": 446390272,
                "size_total": 511418368
            }
        ],
        "ansible_nodename": "schoolserver.lan",
        "ansible_os_family": "RedHat",
        "ansible_pkg_mgr": "yum",
        "ansible_processor": [
            "ARMv7 Processor rev 5 (v7l)",
            "ARMv7 Processor rev 5 (v7l)",
            "ARMv7 Processor rev 5 (v7l)",
            "ARMv7 Processor rev 5 (v7l)"
        ],
        "ansible_processor_cores": 1,
        "ansible_processor_count": 4,
        "ansible_processor_threads_per_core": 1,
        "ansible_processor_vcpus": 4,
        "ansible_product_name": "NA",
        "ansible_product_serial": "NA",
        "ansible_product_uuid": "NA",
        "ansible_product_version": "NA",
        "ansible_python_version": "2.7.8",
        "ansible_selinux": {
            "status": "disabled"
        },
        "ansible_ssh_host_key_ecdsa_public":
"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNZM55uRsJGPeb0lv5yCoTlhErfEt1wr3bN2cAScr12kY+deMmsWAU+Z+ZM4Mw4eTd8dQorGRyi+pNjlIXhwrK4=",
        "ansible_ssh_host_key_rsa_public":
"AAAAB3NzaC1yc2EAAAADAQABAAABAQDBGMITXg1kTQt+OQTsTG/6ore3pmXxy0HxbJ9noH1DrDPmVFGFqiqVaroYZQ6cb4zuhq2vP5htG/YmyaRdzZUijt5TJg3WUAp5LDAWYMoymmx0yqMBuzBH5xJff9md4kbXKc4nT5TnO2GtAeUWg4YYGZ3qr5jyj/xU6NmE3h9KW780alP2o0H0I9caRWazj6ZEe0VHbm+N79wBdwEXvytdGHYdVHS4aeEG1rukY+94qWi1ZhJqZe/FGQjGknsK3gtb80eiYbXt5GTmSO+yPeFO4sd5hG9qa6P6UzW4m8bz2WIuIC2mquqQlGWEgOSBSAjVM/ekeWO735OFGMEVJ9Op",
        "ansible_swapfree_mb": 488,
        "ansible_swaptotal_mb": 488,
        "ansible_system": "Linux",
        "ansible_system_vendor": "NA",
        "ansible_user_id": "root",
        "ansible_userspace_bits": "32",
        "ansible_virtualization_role": "NA",
        "ansible_virtualization_type": "NA",
        "ansible_wlan0": {
            "active": true,
            "device": "wlan0",
            "ipv6": [
                {
                    "address": "fe80::eade:27ff:fea2:9577",
                    "prefix": "64",
                    "scope": "link"
                }
            ],
            "macaddress": "e8:de:27:a2:95:77",
            "module": "r8188eu",
            "mtu": 1500,
            "promisc": true,
            "type": "ether"
        },
        "module_setup": true
    },
    "changed": false
}

**Comment by jvonau** [comment]
After pushing #266 this is good to go, the ks.cfg holds the magic and kicked off with mkiso.sh

**Comment by jvonau** [comment]
incorporated into #272

**Pull request closed without merging**
