### PR TITLE
install-init changes

### PR DESCRIPTION
**Pull request by tim-moody**
only run if /etc/xsce/config_vars.yml doesn't exist
add don't track (used to be here, but disappeared sometime)

### CODE REVIEW

**Comment by jvonau** [comment]
That git call has always been in local_facts.fact.j2, is only run during 0-once, but a git reset might undo that anyways. Remove from  local_facts.fact.j2? . I like having the call in install-init. Once this is pushed I have to fix the the kickstart files logic, I'm looking for the results in the logs and was testing the number of failed=0 that are present.

**Comment by tim-moody** [comment]
I thought it was somewhere and I probably put it there; it's my style of comment.
I guess what happened is that I did a clone and cp from xsce-local, but later did a pull without ever running install-console or any other script so local_vars got overwritten.  This change wouldn't fix that, but would allow install-init to be run to create an image without anything being installed.

**Comment by tim-moody** [comment]
maybe this belongs in the xsce-local cp-ans script.

**Comment by jvonau** [comment]
think "cd $XSCE_DIR" is still needed to put you in the directory for the git command

**Comment by jvonau** [comment]
I think "if [ ! -f xsce.yml ]" should be install-init.yml

**Comment by jvonau** [comment]
Ok, the cd is not needed, we agreeded not to run ansible from outside of $XSCE_DIR and we are in the git repo when running.

**Pull request merged**
