### PR TITLE
RFC add xsce_lan_enabled xsce_wan_enabled

### PR DESCRIPTION
**Pull request by jvonau**
As a continuation of the conversation in #221  Is this the general way you envision how the concept should look? If this is looks good please close #221. I'm testing this over the next bit.

### CODE REVIEW

**Comment by jvonau** [comment]
unplugging wan gives lancontoller 
unplugging lan gives appliance
both wan & lan plugged gives gateway
both wan & lan plugged + xsce_lan_enabled: False gives appliance
both wan & lan plugged + xsce_wan_enabled: False gives lancontoller
Think that is about it.

**Comment by tim-moody** [comment]
100% yes to the previous comment; that is what I was thinking.  We need to add that in each case ansible has to be run afterward in order to adjust the settings unless we move to automatically reconfiguring the network on boot, but that may go too far for now.

**Comment by tim-moody** [comment]
Looking at the code, am I right that there are now for both lan and wan:

_enabled - for the above logic
user iface - for the unlikely case where the user needs to override the device
discovered iface - intermediate result of discovery
iface - final result of devices that will be used or none
?

I assume the first must be set by the user or a default and the second is optional to handle the rare case where the user needs to override the device.  

The last two are working variables and should be set and defined in computed_vars.  I would remove these from default_vars and initialize them in computed_vars.

I would change default_vars as follows

#Read docs/NETWORKING.rst
xsce_wan_enabled: True
xsce_lan_enabled: True

# only change this is if you know what you are doing and then rarely
# user_lan_iface: some device
# user_wan_iface: some device

Then logic like

- name: Clone user configured LAN fact from vars/
  set_fact:
    user_lan_iface: "{{ xsce_lan_iface }}"
  when: 'xsce_lan_iface != ""'

becomes

- name: Use overridden device name
  set_fact:
    xsce_lan_iface: {{ user_lan_iface  }
  when: 'user_lan_iface  is defined

**Comment by tim-moody** [comment]
the bolds above were meant to have hash marks marking a comment

\# only change this is if you know what you are doing and then rarely
\# user_lan_iface: some device
\#user_wan_iface: some device

**Comment by jvonau** [comment]
On Sun, Feb 22, 2015 at 9:36 AM, Tim Moody <notifications@github.com> wrote:

> Looking at the code, am I right that there are now for both lan and wan:
>
> _enabled - for the above logic
> user iface - for the unlikely case where the user needs to override the
> device
> discovered iface - intermediate result of discovery
> iface - final result of devices that will be used or none
> ?
>
More or less yes


> I assume the first must be set by the user or a default and the second is
> optional to handle the rare case where the user needs to override the
> device.
>
the _enabled flags are intended to be exposed in vars/ with a default of
True, the rest becomes working variables.


>  The last two are working variables and should be set and defined in
> computed_vars.
>
So leave user_*an_iface exposed in vars/ in place of xsce_*an_iface?
This block of code can live in 1-prep, maybe it should I did that in #214.


> I would remove these from default_vars and initialize them in computed_vars
>
I didn't see an example of using "set" in  computed_vars just "set_facts",
thought you needed to use default_vars to setup that so I ran with it. Duh,
now that I see that I can do just that with the code used I for
xsce_network_mode that should less of a pain. Let me work that up...

> I would change default_vars as follows
>
> #Read docs/NETWORKING.rst
> xsce_wan_enabled: True
> xsce_lan_enabled: True
> only change this is if you know what you are doing and then rarely user_lan_iface:
> some device user_wan_iface: some device
>
> Then logic like
>
>    - name: Clone user configured LAN fact from vars/ set_fact:
>    user_lan_iface: "{{ xsce_lan_iface }}" when: 'xsce_lan_iface != ""'
>
> becomes
>
>    - name: Use overridden device name set_fact: xsce_lan_iface: {{
>    user_lan_iface } when: 'user_lan_iface is defined
>
>
I'd prefer to declare with a known variable and record the result anyway
but that is possible also. Not to worry I knew you weren't yelling. ;)

**Comment by georgejhunt** [comment]
I'm finding that NetworkManager is failing to start with an error:

NetworkManager: undefined symbol: dbus_g_method_invocation_get_g_connection

I egrep-ed /etc/NetworkManager not finding the symbol -- any suggestions?

**Comment by jvonau** [comment]
What version of NM? That sounds like a recent NM or dbus upgrade broke
something, can you check for recent activity in /var/log/yum.log (might of
been rotated out)

**Comment by jvonau** [comment]
Think this is about feature complete. Here is a quick hint, if you ever want to have a look at the current diff in a PR you can append .diff to the PR's url, so for this PR that is: https://github.com/XSCE/xsce/pull/222.diff but I prefer to view the changes at PR/files which is https://github.com/XSCE/xsce/pull/222/files for this one.

**Comment by georgejhunt** [comment]
Jerry

Thanks for the suggestion. I did a yum update, and restart, and it all ran
to completion

**Comment by georgejhunt** [comment]
I like the changes this commit intruduces. It seems clearer. Of course,
there's lots of testing ahead!

**Comment by tim-moody** [comment]
is any further testing required?

**Comment by tim-moody** [comment]
In case it matters, did gw install and then removed lan nic:

[root@schoolserver xsce]# systemctl status dhcpd
dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/etc/systemd/system/dhcpd.service; disabled)
   Active: failed (Result: exit-code) since Mon 2015-02-23 09:33:51 EST; 8min ago
 Main PID: 1056 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/dhcpd.service

Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: Not configured to listen on any interfaces!
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: This version of ISC DHCP is based on the release available
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: on ftp.isc.org.  Features have been added and other changes
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: have been made to the base software release in order to make
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: it work better with this distribution.
Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
Feb 23 09:33:51 schoolserver.lan systemd[1]: dhcpd.service: main process exited, code=exited, status=1/FAILURE
Feb 23 09:33:51 schoolserver.lan systemd[1]: Unit dhcpd.service entered failed state.

do we care if dhcpd is failed instead of inactive?

[root@schoolserver xsce]# cat /etc/xsce/xsce.ini
[version]
xsce_branch = RFC-1
xsce_commit = 913eb8fe747f55a9d3f643cd499fe6917aa8766a
install_date = 2015-02-23T14:33:23Z

[location]
xsce_base = /opt/schoolserver
xsce_dir = /opt/schoolserver/xsce

[network]
wan_enabled = True
lan_enabled = True
detected_gateway = p2p1
detected_lan =
user_gateway = auto
user_lan = auto
computed_gateway = p2p1
computed_lan = none
xsce_network_mode = Appliance

**Comment by tim-moody** [comment]
on x64 vm installed with two nics
  xsce.ini looks right, ip addr looks right
removed lan nic
  results in prev comment
removed wan nic and added back lan nic
  xsce.ini looks right, ip addr looks right, 
  systemct status { dansguardian, squid, named, dhcpd, wondershaper}
  named, dhcpd active, others inactive

**Comment by tim-moody** [comment]
I notice that both network and gateway still exist as tags.  Is that right?  What does each do?

**Comment by tim-moody** [comment]
on xo4
install-console with one nic (wifi) - got an appliance
connect usb dongle ./runtags network,gateway - got gateway, dansguardian, squid, named, dhcpd, wondershaper all active
disconnect usb dongle ./runtags network,gateway - got appliance, dansguardian, squid, named, dhcpd, wondershaper all inactive (or failed: dhcpd)

**Comment by jvonau** [comment]
That currently would be the case just after install but before a reboot,
when we install there is an unconditional service restart for dhcpd at that
point in time.

On Mon, Feb 23, 2015 at 8:47 AM, Tim Moody <notifications@github.com> wrote:

> In case it matters, did gw install and then removed lan nic:
>
> [root@schoolserver xsce]# systemctl status dhcpd
> dhcpd.service - DHCPv4 Server Daemon
> Loaded: loaded (/etc/systemd/system/dhcpd.service; disabled)
> Active: failed (Result: exit-code) since Mon 2015-02-23 09:33:51 EST; 8min
> ago
> Main PID: 1056 (code=exited, status=1/FAILURE)
> CGroup: /system.slice/dhcpd.service
>
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: Not configured to listen on
> any interfaces!
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: This version of ISC DHCP is
> based on the release available
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: on ftp.isc.org. Features
> have been added and other changes
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: have been made to the base
> software release in order to make
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]: it work better with this
> distribution.
> Feb 23 09:33:51 schoolserver.lan dhcpd[1056]:
> Feb 23 09:33:51 schoolserver.lan systemd[1]: dhcpd.service: main process
> exited, code=exited, status=1/FAILURE
> Feb 23 09:33:51 schoolserver.lan systemd[1]: Unit dhcpd.service entered
> failed state.
>
> do we care if dhcpd is failed instead of inactive?
>

I was checking for listening ports, I would prefer not to see this error,
but what puzzles me is

TASK: [gateway | Disable dhcpd service]
***************************************
ok: [127.0.0.1]

TASK: [gateway | Enable dhcpd service]
****************************************
skipping: [127.0.0.1]

systemctl is-enabled dhcpd
disabled

but the state=stopped part is not effective, investagating.

**Comment by jvonau** [comment]
Those tags should really be combined, you need to use both to change the
network/gateway settings.

**Comment by curtathompson** [comment]
Hi everyone,

I have an x86 laptop I just put XSCE onto.  Did we have MAC address
filtering enabled (to limit clients, e.g. keep phones and other unknown
devices from using it), or can that only be set on the AP?

I look through the instructions a bit, but didn't see any reference to
MAC filtering.  I thought we had that at some of our deployments, or
maybe i confused that with the website whitelist.

The git-based Install process and GUI configuration option make for a
much better UX!  It has certainly come a long way from the first version
I tested (XSCE 0.4).

Thanks

**Pull request merged**
