### PR TITLE
kalite-0.16

### PR DESCRIPTION
**Pull request by jvonau**
for master - use provide python rpms in place of pip when possible.

### CODE REVIEW

**Comment by tim-moody** [comment]
with most kalite version changes the dependencies are the easy part.  the hard part is that the installation process changes thus breaking our scripts, so can you verify that it actually installs once the new dependencies are handled.

**Comment by davelab6** [comment]
@jvonau why not prefer pip?

**Comment by jvonau** [comment]
@davelab6 we can discuss the best practices use of pip on the mailing list
@tim-moody this is ready for testing

**Comment by tim-moody** [comment]
This worked for me on a VM, except that:
1) changed /opt/schoolserver/xsce/roles/kalite/tasks/install.yml  ka-lite==0.16.0 to >=
2) seems the docs are missing in the pip package

**Comment by jvonau** [comment]
So we always want to run the latest? The doc need the link created in 6fe534b. What about preffering rpms over pip?

**Comment by tim-moody** [comment]
we probably want the latest 0.16, but who knows about 0.17.
the doc link doesn't do any good if upstream didn't put anything in the linked to directory.
[root@schoolserver xsce]# ll /usr/share/kalite/docs/_build/html/usermanual
total 0
[root@schoolserver xsce]# ll /usr/share/kalite/docs/_build/html/developer_docs
total 0
[root@schoolserver xsce]# ll /usr/share/kalite/docs/_build/html/installguide
total 0

I didn't find an rpm.

**Comment by tim-moody** [comment]
maybe  pip install "kalite>=0.16,<0.17"

**Comment by jvonau** [comment]
I like the <0.17... Thinks the docs are generated on the fly, but needs the link to poke the process to start... Please look at the whole patch there are bug fixes also.

**Comment by jvonau** [comment]
Maybe we have different ka-lite versions?
pip show ka-lite (0.16.0)  

ls -la /usr/share/kalite/docs/_build/html/developer_docs:
-rw-r--r-- 1 root root 11690 Apr  9 11:36 accessibility.html
-rw-r--r-- 1 root root 14598 Apr  9 11:36 behave_testing.html
-rw-r--r-- 1 root root  6819 Apr  9 11:36 contributing.html
-rw-r--r-- 1 root root  8977 Apr  9 11:36 documentation.html
-rw-r--r-- 1 root root 12317 Apr  9 11:36 environment.html
-rw-r--r-- 1 root root 25456 Apr  9 11:36 front_end_code.html
-rw-r--r-- 1 root root 10654 Apr  9 11:36 index.html
-rw-r--r-- 1 root root 17397 Apr  9 11:36 javascript_testing.html
-rw-r--r-- 1 root root  7263 Apr  9 11:36 logging.html
-rw-r--r-- 1 root root  7641 Apr  9 11:36 profiling.html
-rw-r--r-- 1 root root  8072 Apr  9 11:36 utility.html

**Comment by tim-moody** [comment]
on the vm I have 0.16.1 and on the rpi3 0.16.2 (both using >=0.16.0) and neither has the docs, so they must have a packaging error.

**Comment by tim-moody** [comment]
more problematic for us is that while 0.16.1 went to completion on the vm, 0.16.2 stopped on the kalite start for reasons I don't understand:
2016-04-13 20:08:54,964 p=2123 u=root |  <job 157643331985.3126> finished on 127.0.0.1
2016-04-13 20:08:54,966 p=2123 u=root |  TASK: [kalite | Finish setup by running kalite start] *************************
2016-04-13 20:09:07,293 p=2123 u=root |  failed: [127.0.0.1] => {"ansible_job_id": "6303282767.3199", "changed": false, "cmd": "/root/.ansible/tmp/ansible-tmp-1460578135.02-172986961238210/command /root/.ansible/tmp/ansible-tmp-1460578135.02-172986961238210/arguments", "failed": 1, "finished": 1}
2016-04-13 20:09:07,295 p=2123 u=root |  msg: [Errno 2] No such file or directory
2016-04-13 20:09:07,296 p=2123 u=root |  <job 6303282767.3199> FAILED on 127.0.0.1
2016-04-13 20:09:07,298 p=2123 u=root |  FATAL: all hosts have already failed -- aborting

but when I did
export KALITE_HOME=/library/ka-lite
kalite start
it worked

**Pull request closed without merging**
