### PR TITLE
Awstats

### PR DESCRIPTION
**Pull request by georgejhunt**
I want to pull this into a test install, to check for typo's before I merge it into master

### CODE REVIEW

**Comment by jvonau** [comment]
I would just change the squid-xs.conf for the logging changes, or we risk
loosing the change if squid's playbook is rerun.

**Comment by tim-moody** [comment]
+#
+DirData="/var/lib/awstats" in the config looks wrong

where is the url to access this?

**Comment by georgejhunt** [comment]
As you point out, changing squid-xs.conf will just get wiped out if the
playbook is run again. I don't think we have a clean way to deal with one
service modifying another. I'll just comment it out for now.

**Comment by georgejhunt** [comment]
At line 203 of ./templates/apache-awstats.conf it is set to what I wanted.
Where did you see it set to /var/lib/awstats? I must have missed it.

**Comment by tim-moody** [comment]
OK.  I must have been looking at one of the earlier commits before you set that.

**Pull request merged**
