### PR TITLE
Defaults: make consistent -- install:true, enabled:false

### PR DESCRIPTION
**Pull request by georgejhunt**
The current defaults show up in admin console, and don't make much sense on centos, or fc23

### CODE REVIEW

**Comment by jvonau** [comment]
I'm in general agreement but usb-lib can stay as true, it won't be another
daemon running. We could default everything after install console to off
which might help on resource tight machines. Thoughts?

**Comment by georgejhunt** [comment]
I enabled usb-lib, and will give it a day, before i pull it in.

**Comment by tim-moody** [comment]
no iiab, no osm

**Comment by georgejhunt** [comment]
This PR got mixed up with other commits. Deleting and starting over

**Pull request closed without merging**
