### PR TITLE
Yum fix

### PR DESCRIPTION
**Pull request by jvonau**
Thought this was the fix that came out of the conversation in #516

### CODE REVIEW

**Comment by tim-moody** [comment]
these two approaches are not identical.

one says get the latest if you have an internet connection

the other says once the thing is installed it's good enough

the first was an attempt to retain the original author's logic, but not sure if it was needed or desirable.

**Comment by jvonau** [comment]
On Fri, Dec 18, 2015 at 1:18 PM, Tim Moody <notifications@github.com> wrote:

> these two approaches are not identical.
>
Yes, I know.


> one says get the latest if you have an internet connection
>
> the other says once the thing is installed it's good enough
>
Yes, agreed.

> the first was an attempt to retain the original author's logic, but not
> sure if it was needed or desirable.
>
Must of missed this one while the playbook was not part of the stock
install, just an optional component that was broken at one point in time.
For the sake of consistency, lets stick to the same logic that every other
playbook that appears in xsce-from-console.yml uses.

**Comment by tim-moody** [comment]
just bear in mind that if there are fixes to pathagar they won't be picked up.  it's a judgement call.

**Comment by jvonau** [comment]
Please fully explain your concerns because I fail to see them. If this module is that flaky maybe we should just disable it for the stock install?

**Pull request merged**
