### PR TITLE
fixes:

### PR DESCRIPTION
**Pull request by tim-moody**
duplicate backup in xo.yml
  fault if whitelist not exist
  find devices script
  add owncloud to mysql true condition
  lengthen timout on kalite

### CODE REVIEW

**Comment by georgejhunt** [comment]
There are a lot of whitespace changes in this commit. What editor, and what settings are you using.
I usually use vim with expand tab and tabspace=4. If we all do the same, the significant changes will not be burried in the fluff.

On the substance, you've been doing some good debugging.

**Comment by tim-moody** [comment]
I edit in UltraEdit on a PC.   the docs say the default is convert tabs to spaces with 4 spaces.

previously I was introducing spurious spaces because of space on the end of lines through cut and paste.

I recently changed my setting so trim that space when saving.

can you cite an example of a line that has whitespace only changes.

**Comment by georgejhunt** [comment]
On Tue, Mar 10, 2015 at 8:37 PM, Tim Moody <notifications@github.com> wrote:

> I edit in UltraEdit on a PC. the docs say the default is convert tabs to
> spaces with 4 spaces.
>
> previously I was introducing spurious spaces because of space on the end
> of lines through cut and paste.
>
> I recently changed my setting so trim that space when saving.
>
> can you cite an example of a line that has whitespace only changes.
>

I was looking at the files changed for this PR at
https://github.com/XSCE/xsce/pull/235/files

**Comment by tim-moody** [comment]
>From: georgejhunt 
>Sent: Wednesday, March 11, 2015 10:14 AM
>To: XSCE/xsce 
>Cc: Tim Moody 
>Subject: Re: [xsce] fixes: (#235)
>
>On Tue, Mar 10, 2015 at 8:37 PM, Tim Moody <notifications@github.com> wrote:
>
>> I edit in UltraEdit on a PC. the docs say the default is convert tabs to
>> spaces with 4 spaces.
>>
>> previously I was introducing spurious spaces because of space on the end
>> of lines through cut and paste.
>>
>> I recently changed my setting so trim that space when saving.
>>
>> can you cite an example of a line that has whitespace only changes.
>>
>
>I was looking at the files changed for this PR at
>https://github.com/XSCE/xsce/pull/235/files
>

the ones I see have space removed from the end of the line as I guessed before, so nothing to do with tabs.

**Pull request merged**
