### PR TITLE
RFC console speed up when networking has not changed.

### PR DESCRIPTION
**Pull request by jvonau**
We can skip the network playbook if the detected network layout matches the user's wishes in the gui.

### CODE REVIEW

**Comment by tim-moody** [comment]
I think gui_desired_network_role will be defined as soon as the console has been run once

**Comment by jvonau** [comment]
That would be the key, if user wants a certain layout and that matches what is detected I see no point in running through the playbook to make no changes, otherwise run the playbook.

**Comment by tim-moody** [comment]
agreed.  is that what - { role: network, tags: ['services','base','network'], when: not gui_desired_network_role is defined } does?

**Comment by jvonau** [comment]
On Sat, Aug 22, 2015 at 12:01 PM, Tim Moody <notifications@github.com>
wrote:

> agreed. is that what - { role: network, tags:
> ['services','base','network'], when: not gui_desired_network_role is
> defined } does?
>
>
Untested,  I was looking to gather thoughts before proceeding. I'm hoping
that it does and will report back in this PR.

**Comment by jvonau** [comment]
part of PR #510

**Pull request closed without merging**
